config/routes.rb
Rails.application.routes.draw do
 root 'static_pages#home'
 get 'auth/facebook', as: "login"
 get 'auth/facebook/callback', to: 'sessions#create'
 get 'logout'   => 'sessions#destroy', as: "logout"
 get 'users', to: "users#index", as: "users"
 get 'users/:id', to: "users#show", as: "user" 
 get 'users/:id/edit', to: "users#edit", as: "edit_user"
 patch 'users/:id', to: "users#update"
 get 'newsfeed', to: "posts#index", as: "posts"
  post 'newsfeed', to: "posts#create"
  post 'users/:id/post', to: "posts#create", as: "receive_post"
 delete 'posts/:id', to: "posts#destroy", as: "delete_post"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :receiver, class_name: 'User'
  default_scope { order(created_at: 'DESC') }
  
  has_attached_file :image, styles: { medium: "500x500>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts
    default_scope { order(created_at: 'DESC') }
  # Initializes or updates user object when logging in with Facebook
  def self.from_omniauth(auth)
    where(fb_id: auth.uid).first_or_create do |user|
      user.oauth_provider = auth.provider
      user.fb_id = auth.uid
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.name ||= auth.info.name
      user.avatar_url ||= "http://graph.facebook.com/#{auth.uid}/picture?width=500"
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  
    def requires_logged_in
      if current_user == nil
        redirect_to root_url #Only happens if current_user is equal to nil
      end
    end
    
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue
        session[:user_id] = nil
        return nil
      end
    end
    
    helper_method :current_user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :requires_logged_in, only: [:create, :destroy]
  
  def index
    @post = Post.new
    @posts = Post.all
  end
  
  def create
    @post = current_user.posts.create(post_params)
    if params[:id]
      @post.receiver_id = params[:id].to_i
      @post.save
      redirect_to user_path(params[:id])
    else
      @post.save
      redirect_to newsfeed_url
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    if current_user == @post.user
      @post.destroy
    end
    redirect_to newsfeed_url
  end
  
  private
  
    def post_params
      params.require('post').permit('message', 'image')
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
end

class UsersController < ApplicationController
  
  def edit
    @user = User.find(params[:id])
  end  
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end
  
  
  def index
    @users = User.all
  end
  
  def show
      @user = User.find(params[:id])
      @post = Post.new
      @posts = Post.where("user_id = ? or receiver_id = ?", @user.id, @user.id)
  end
  
  private
  
    def correct_user
      # .to_i converts values to integers here because params[:id] is a string
      # Without this current_user.id and params[:id] would never match
      if current_user.id != params[:id].to_i
        redirect_to root_url
      end
    end
    
    def user_params
      params.require(:user).permit(:bio)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_url %>">Memespace</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li id="newsfeed-link"><a href="<%= newsfeed_path %>">News Feed</a></li>
          <li id="users-link"><a href="<%= users_path %>">Users</a></li>
          <% if current_user %>
            <li id="profile-link"><a href="<%= user_path(current_user) %>">Profile</a></li>
            <li><a href="<%= logout_path %>">Log Out</a></li>
          <% else %>
            <li><a href="<%= login_path %>">Log In</a></li>
          <% end %>
        </ul>
      </div>
    </div>
</nav>

<script>
 <% if request.original_url == users_url %>
   $('#users-link').addClass('active');
 <% elsif current_user && request.original_url == user_url(current_user) %>
   $('#profile-link').addClass('active');
 <% end %>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Memespace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
 <%= render 'layouts/navbar' %>
 <%= yield %>
</div>

</body>
</html>

app/views/posts/index.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3 col-sml-12">
        <h2 align="center">News Feed</h2>
        
       <%= render 'shared/feed' %>
    </div>
</div>

app/views/shared/_feed.html.erb
<% if current_user %>
    <div class="panel panel-default">
      <div class="panel-body">
        <% if @user %>
        
          <%= form_for(@post, url: receive_post_path(@user.id), :html => { :multipart => true }) do |f| %>
              <div class="form-group">
                  <input type="text" name="post[message]" class="form-control" placeholder="What's on your mind?"/>
              </div>
              <div class="form-group">
              <%= f.file_field :image %>
            </div>
              <input type="submit" value="Submit" class="btn btn-primary"/>
          <% end %>
        <% else %>
          <%= form_for(@post, :html => { :multipart => true }) do |f| %>
              <div class="form-group">
                  <input type="text" name="post[message]" class="form-control" placeholder="What's on your mind?"/>
              </div>
              <div class="form-group">
              <%= f.file_field :image %>
            </div>
              <input type="submit" value="Submit" class="btn btn-primary"/>
          <% end %>
        <% end %>
      </div>
    </div>
<% end %>
<% @posts.each do |post| %>
    <div class="panel panel-default">
      <div class="panel-body">
          <h4 style="margin-top: 0px;">
              <a href="<%=user_path(post.user)%>"><%= post.user.name %></a>
              <% if current_user == post.user %>
                  | <%= link_to 'Delete', delete_post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
          </h4>
         
          <%= post.message %>
      </div>
    </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to Memespace master More changes on home</h1>
  <p>even more changes 222</p>
  <p>
    <% if current_user %>
      Welcome, <%=current_user.name%>!
      <br>
      <a class="btn btn-lg btn-primary" href="/logout" role="button">Log Out</a> 
    <% else %>
      <a class="btn btn-lg btn-primary" href="/auth/facebook" role="button">Log In With Facebook</a> 
    <% end %>
  </p>
</div>

app/views/users/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-12">
        <h2 align="center">Updating <%=@user.name%></h2>
        <%= form_for(@user) do |f| %>
            <div class="form-group">
                <textarea name="user[bio]" class="form-control" placeholder="Bio"><%=@user.bio%></textarea>
            </div>
            <input type="submit" value="Submit" class="btn btn-primary"/>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <% @users.each do |user| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="<%=user.avatar_url%>" alt="Avatar" style="width: 100%;">
        <div class="caption">
    <h3><%=user.name%></h3>
    <p><%=user.bio%></p>
    <p><a href="<%=user_path(user)%>" class="btn btn-primary" role="button">Profile</a></p>
  </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-3 col-sm-12">
        <img src="<%=@user.avatar_url%>" alt="Avatar" style="width: 300px; max-width: 100%;">
        <h1><%=@user.name%></h1>
         <p><%=@user.bio%></p>
        <% if current_user.id == @user.id %>
            <p><a href="<%=edit_user_path(@user.id)%>" class="btn btn-primary" role="button">Edit Profile</a></p>
        <% end %>
    </div>
    <div class="col-md-9 col-sm-12">
        <%= render 'shared/feed' %>
    </div>
</div>